### PR TITLE
 adding Decred 

### PR DESCRIPTION
**Pull request by jackliv3r**

### CODE REVIEW

**Comment by ummjackson** [comment]
Thanks @jackliv3r, really helpful. Is there a website where we can get a breakdown of what makes up that "solo miners" category? I would like to put a number in the mining distribution field, and I'm sure there are some bigger miners in that group relative to others.

**Comment by jackliv3r** [comment]
really hard to say, consider that as far we know solo miners are all ASICs/FPGAs and many more will come in next months, there are five distinct manufacturers ( obelisk, baikal, halong, dcrasic and bitmain ) so could be many different users and small farms for now.

a "safe" number on how many miners are in control could be 2 = solo miners + the largest pool.

**Comment by ummjackson** [comment]
Makes sense, thanks @jackliv3r - would you mind updating the number to 2 for this PR and maybe adding into the notes section why it's 2? Then I will merge.

**Comment by xaur** [comment]
Briefly looking at the patch, the `consensus_distribution` doesn't include the Proof-of-Stake part of Decred consensus system. There are a dozen of [stakepools](https://decred.org/stakepools/) and a portion of solo stakers. PoS layer is the "killer feature" -- it _approves_ PoW miner blocks and keeps miners in check. Omitting it makes Decred look like yet another pure PoW coin that is dominated by a single pool.

**Comment by ummjackson** [comment]
This was never updated. Please submit a new PR with all the required details.

**Pull request closed without merging**
