### PR TITLE
Add Qtum

### PR DESCRIPTION
**Pull request by Gyunikuchan**

### CODE REVIEW

**Comment by chrisco255** [comment]
Are there any updates on getting Qtum merged in here? This is one of the most decentralized platforms (7000+ nodes with no minimum proof of stake consensus) and it's a top 20 coin. Would love to see it represented here.

**Comment by ummjackson** [comment]
Hi @chrisco255 - I need a better explanation of where the consensus distribution number is coming from. The linked source doesn't directly provide that number and I have no idea of the methodology used.

**Comment by Gyunikuchan** [comment]
Initially i've been reliant on another Jackson's blog for the data
https://medium.com/@jb395official

But to check it for myself, I've created a script for scraping some these data:
https://github.com/Gyunikuchan/qtum-stats

Here are the results:
consensus_distribution: 234 addresses over 24 hours
consensus_distribution: 455 addresses over 48 hours
consensus_distribution: 822 addresses over 4 days
consensus_distribution: 1192 addresses over 7 days
consensus_distribution: 2900 addresses over a month
wealth_distribution: 72.71400000000003% held by the top 100 addresses

**Comment by Gyunikuchan** [comment]
@ummjackson I've update the script to include more statistics.
My take is that Qtum's consensus distribution should be 47 / 68 / 72 entities depending on the length of measurement. I'm not certain about the time frames used for the other projects.

//////////////////////////////////////////////////////
Qtum
//////////////////////////////////////////////////////
======== Consensus Distribution ========
1 Day Stats
303 addresses over 605 blocks
47 of the top addresses generated 51% of the blocks
Producer #1: 33 blocks
Producer #2: 32 blocks
Producer #3: 31 blocks
Producer #4: 16 blocks
Producer #5: 13 blocks
Producer #10: 6 blocks
Producer #50: 3 blocks
Producer #100: 1 blocks

1 Week Stats
1218 addresses over 4213 blocks
68 of the top addresses generated 51% of the blocks
Producer #1: 224 blocks
Producer #2: 215 blocks
Producer #3: 147 blocks
Producer #4: 90 blocks
Producer #5: 87 blocks
Producer #10: 47 blocks
Producer #50: 13 blocks
Producer #100: 7 blocks

1 Month Stats
2910 addresses over 18023 blocks
72 of the top addresses generated 51% of the blocks
Producer #1: 974 blocks
Producer #2: 767 blocks
Producer #3: 738 blocks
Producer #4: 430 blocks
Producer #5: 323 blocks
Producer #10: 205 blocks
Producer #50: 59 blocks
Producer #100: 29 blocks

======== Consensus Distribution ========
36.3244% held by the top 10 addresses
64.67959999999998% held by the top 50 addresses
72.89980000000003% held by the top 100 addresses

**Comment by Gyunikuchan** [comment]
To further verify the methodology, I've ran the script against eth and got a reasonable result of 3:
https://github.com/Gyunikuchan/crypto-stats/blob/master/results/ethereum.results.md
https://github.com/Gyunikuchan/crypto-stats/blob/master/results/qtum.results.md

**Comment by ummjackson** [comment]
Hi @Gyunikuchan - I appreciate the lengthy explanation, very good stuff! Looking at the chart here for the 1 day: https://github.com/Gyunikuchan/crypto-stats/blob/master/results/qtum.results.md#period-1-day-fri-may-25-2018-232015-gmt0800---sat-may-26-2018-232015-gmt0800

I count 204 blocks in total, so around 104 would equal 51% of blocks in a 24 hour period. I see from these stats that ~5 addresses were responsible for 104 blocks, so would 5 not be the number?

**Comment by Gyunikuchan** [comment]
thx @ummjackson 
I've updated the pull request to reflect the last gathered stats as on 26th May

The total # of blocks for that day is actually **592**, so **45** of the top block producers is needed to mount a 51% attack (actual threshold in the algorithm was 50%)

The producer table shown is non-exhaustive, it only shows a sample of producers to give an idea of what the distribution looks like (#1-20, #30, #40, #50, #100)

**Comment by Gyunikuchan** [comment]
If you're interested in the methodology, it can be found here:
https://github.com/Gyunikuchan/crypto-stats/blob/master/src/common/producer.service.ts

**Comment by JB395** [comment]
I am the “other Jackson”, a Qtum researcher and blogger.
Are you looking for the number of node validators (Qtum staking wallets) needed to, on average, produce half of the 600 blocks per day? If so, I can separately calculate using my methodology (unique addresses among block reward winning wallets). Note that the number of validators would be dependent on their staking weight (number of QTUM they commit to staking), and this number is different than the rich list, because the biggest rich list addresses are not staking.

**Comment by JB395** [comment]
Hello **@ummjackson**, following your thread in the PR for ADDR, I reviewed the block producers for July 20 – July 26. For a total of 4,188 blocks (#193,422 to 197,629) there were **41** staking nodes needed to publish 50% of the blocks, or 45 needed to publish 51% of the blocks. My methodology uses Excel string matching with data taken from the qtum.info explorer.

This result compares well with @Gyunikuchan’s result in May. I hope you can find time to review this PR and thanks for the consideration.

**Pull request merged**
