### PR TITLE
Create peercoin.yml

### PR DESCRIPTION
**Pull request by sunnyqueen**

### CODE REVIEW

**Comment by ummjackson** [comment]
Thanks @sunnyqueen! Do you know whether that table with the mining distribution is accurate for staking? It looks like it's combining the reward mechanism (PoW) with the consensus protocol (PoS) for Peercoin and hence the number might be off... any ideas?

**Comment by sunnyqueen** [comment]
I didn't take the combined PoW and PoS, it is from the top 100, counted the addresses until they add up to > 50%
The PoS secures the chain 100%, every address that has coins is able to mint, what would be more accurate is if I could take the number of actually minting addresses that add up to >50% of current minting addresses.
It is not exactly accurate because not all the addresses in this list are minting, but they could all potentially mint.
I don't know what would be the best way to do this, taking the average of the number of addresses that has minted could help, I guess the PoS difficulty says something about the number of coins currently minting, but not about the number of addresses.

**Comment by ummjackson** [comment]
@sunnyqueen I think for PoS the safest way to calculate the # for consensus distribution would be to calculate in the last 7 days what # of validators (stakers) were required to submit >50% of the blocks. Could you help calculate that?

**Comment by sunnyqueen** [comment]
I'm working on it
was AFK for a while

**Comment by ummjackson** [comment]
Never heard back on this. Please submit another PR with updated info.

**Pull request closed without merging**
