### PR TITLE
Adding ARDR

### PR DESCRIPTION
**Pull request by VanBreuk**
Parameters for Ardor (ARDR, https://ardorplatform.org)

### CODE REVIEW

**Comment by ummjackson** [comment]
@VanBreuk Thanks for contributing! I haven't done a lot of research on this blockchain (yet). Before I merge, could you help explain how consensus is reached in Ardor and how many nodes are required each X minutes, seconds etc. to write to the blockchain?

**Comment by VanBreuk** [comment]
Hi @ummjackson and thanks for replying. Ardor is a scalable evolution of the Nxt blockchain ( which was the first 100% PoS ledger) and the consensus logic is essentially the same as in Nxt, see https://nxtwiki.org/wiki/Whitepaper:Nxt#Nxt.E2.80.99s_Proof_of_Stake_Model
The Ardor platform separates the security/main chain (which uses the native ARDR token for the PoS consensus) from the transactional/child chains. Every child chain in the system operates with its own native token, and its transactions are packed together by special nodes called bundlers, that pay ARDR fees to register the child chain transaction hashes in the main chain. This is the gist of it, in short. For a deeper technical overview you can check resources in the website of the developing company - https://www.jelurida.com/ardor-blockchain-platform-design

**Comment by ummjackson** [comment]
Thanks @VanBreuk - I guess I'm not understanding where the "20" comes from for consensus distribution... should this be the # of "bundlers" participating every round?

**Comment by VanBreuk** [comment]
The bundlers for Ardor child chains do not participate in consensus, they only bundle up transactions from their chain to post them to the main ARDR chain as a special kind of transaction, paying a fee in ARDR. Consensus (staking, or what traditionally was called "forging" on Nxt and now Ardor) only happens in the ARDR main chain.
The "20" was a calculation of the current number of entities/accounts that hold together 50% of ARDR, the consensus currency, since in a pure PoS platform the voting/mining power is represented by the stake.

**Comment by ummjackson** [comment]
Thanks @VanBreuk, I don't think we can just use supply distribution for PoS though because that's *potential* to stake rather than active staking - right? Instead, are you able to help calculate the # of entities/accounts who in the last 7 days were required to vote on >50% of the blocks?

**Comment by VanBreuk** [comment]
Sure. I misunderstood "voting/mining power" in your code. While at https://ardor.tools/network you can see the number of online nodes in the network and an estimate of the stake currently generating blocks (total ARDR is almost 1 billion) there is no way to tell at a precise moment how many accounts are actively staking. You can only say that certain account was staking at the moment it generating a block, according to the block header. The rest are statistical estimates.
I've calculated using a script (I can share it if you wanted to replicate results) the number of accounts that generated blocks during the last 7 days, which equals 10,080 blocks, and the count is 330 different accounts. However, the 5 accounts with most blocks add up to 51% of all the generated blocks in this week. Maybe this info is useful.

**Comment by ummjackson** [comment]
@VanBreuk If you could share the script that'd be great, then we can add it here!

**Comment by VanBreuk** [comment]
@ummjackson you can also find Ardor network stats in https://ardorportal.org/monitor but if you want to get the number of generating accounts in an arbitrary number of recent blocks, you can run the script I'm attaching below. The only dependency is `jq`, and you can set `SERVER` as the Ardor server address (default is the path in a normal local install of the official client, https://www.jelurida.com/ardor-client.zip) and `NUMBLOCKS` as the number of blocks you want to count generating accounts for.
```
#!/bin/bash

# Ardor	server address
SERVER="http://localhost:27876"
# Number of last blocks to retrieve for the stats
NUMBLOCKS=300

LASTBLOCK=$(curl -s -d requestType=getState $SERVER/nxt | jq -r '.lastBlockchainFeederHeight')
echo "Last Ardor block height: $LASTBLOCK"
FIRSTBLOCK=$(($LASTBLOCK - $NUMBLOCKS))
echo "First Ardor block height to retrieve: $FIRSTBLOCK"
echo "Retrieving blocks... "

for ((BLOCK=$FIRSTBLOCK; BLOCK<=$LASTBLOCK; BLOCK++))
{
        GETBLOCK=$(curl -s -d requestType=getBlock -d height=$BLOCK $SERVER/nxt | jq -r '.generatorRS')
        echo "$GETBLOCK, " >> generators.tmp
}

echo "Done."
GENSTATS=$(sort -t \n generators.tmp | uniq -c | sort -bgr)
echo "(Number of blocks generated in the last $NUMBLOCKS blocks, generating account)"
echo $GENSTATS
echo "Number of different accounts generating a block in the last $NUMBLOCKS blocks:"
GENCOUNT=$(echo $GENSTATS | wc -w)
echo $((GENCOUNT / 2))
rm generators.tmp
```

**Comment by ummjackson** [comment]
@VanBreuk Merging this but would appreciate an update with latest stats when you're ready and able. Thanks.

**Pull request merged**
