### PR TITLE
Add Particl

### PR DESCRIPTION
**Pull request by LiteBit**

### CODE REVIEW

**Comment by ummjackson** [comment]
@LiteBit - need to understand the logic for how consensus was calculated...

**Comment by LiteBit** [comment]
Hey @ummjackson sorry about delay in answering.

Regarding consensus, I looked at arewedecentralizedyet.com and you have a column "# of entities in control of >50% of voting/mining power" = consensus

I got Particl's 70 in the PR from the Particl explorer on CryptID which shows top wallets. https://chainz.cryptoid.info/part/#!rich
With PART being PoS, I just did the math to collect the number of wallets who would theoretically be staking all their coins to reach >50%

At the time of PR it was 70 wallets = consensus
currently the number is 76 

Sorry again for delay in commenting :)

**Comment by Gyunikuchan** [comment]
A little naive as this assumes that all rich participants are staking...
Active participants should be taken into account when computing this.

e.g. if 20% of total tokens is being staked, it takes only 1 entity to take over

**Comment by LiteBit** [comment]
https://chainz.cryptoid.info/part/#!extraction shows only staking nodes which at the time of this comment is 593 and that accounts for 33.8% of network
image

**Pull request closed without merging**
